name:  dart_multitouch_canvas_example
description:  A sample application

dependencies:
  js:
    git: git://github.com/dart-lang/js-interop.git
  logging: 0.3.1+1
  unittest: 0.3.1+1
  browser: 0.3.1+1